"""host profile fields

Revision ID: 29863b201cb1
Revises: 6238d07c124a
Create Date: 2026-06-21 18:50:08.230176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29863b201cb1'
down_revision: Union[str, None] = '6238d07c124a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('hosts', sa.Column('avatar_url', sa.String(length=600), nullable=True))
    op.add_column('hosts', sa.Column('avatar_storage_id', sa.String(length=300), nullable=True))
    op.add_column('hosts', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('hosts', sa.Column('response_time', sa.String(length=50), nullable=True))
    op.add_column('hosts', sa.Column('phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'phone')
    op.drop_column('hosts', 'response_time')
    op.drop_column('hosts', 'languages')
    op.drop_column('hosts', 'avatar_storage_id')
    op.drop_column('hosts', 'avatar_url')
    op.drop_column('hosts', 'bio')
    # ### end Alembic commands ###
