"""expand unit listing fields

Revision ID: 6238d07c124a
Revises: 2c971b1c6ee8
Create Date: 2026-06-21 15:33:36.226238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6238d07c124a'
down_revision: Union[str, None] = '2c971b1c6ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('property_type', sa.String(length=40), server_default='apartment', nullable=False))
    op.add_column('units', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('units', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('units', sa.Column('beds', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('units', sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('units', sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('units', sa.Column('taxes_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('units', sa.Column('weekly_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('units', sa.Column('monthly_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('units', sa.Column('max_stay_nights', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('instant_book', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('check_in_time', sa.String(length=5), nullable=True))
    op.add_column('units', sa.Column('check_out_time', sa.String(length=5), nullable=True))
    op.add_column('units', sa.Column('pets_allowed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('smoking_allowed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('parties_allowed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('quiet_hours', sa.String(length=100), nullable=True))
    op.add_column('units', sa.Column('smoke_alarm', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('fire_extinguisher', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('first_aid_kit', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('units', sa.Column('emergency_contact', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'emergency_contact')
    op.drop_column('units', 'first_aid_kit')
    op.drop_column('units', 'fire_extinguisher')
    op.drop_column('units', 'smoke_alarm')
    op.drop_column('units', 'quiet_hours')
    op.drop_column('units', 'parties_allowed')
    op.drop_column('units', 'smoking_allowed')
    op.drop_column('units', 'pets_allowed')
    op.drop_column('units', 'check_out_time')
    op.drop_column('units', 'check_in_time')
    op.drop_column('units', 'instant_book')
    op.drop_column('units', 'max_stay_nights')
    op.drop_column('units', 'monthly_discount_percent')
    op.drop_column('units', 'weekly_discount_percent')
    op.drop_column('units', 'taxes_percent')
    op.drop_column('units', 'security_deposit')
    op.drop_column('units', 'service_fee')
    op.drop_column('units', 'cleaning_fee')
    op.drop_column('units', 'beds')
    op.drop_column('units', 'longitude')
    op.drop_column('units', 'latitude')
    op.drop_column('units', 'property_type')
    # ### end Alembic commands ###
