"""availability blocks, seasonal rates, weekend price, min stay

Revision ID: 6366a881815a
Revises: 68f5749a839f
Create Date: 2026-06-20 00:07:37.685185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6366a881815a'
down_revision: Union[str, None] = '68f5749a839f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_block_dates'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_blocks_unit_id'), 'availability_blocks', ['unit_id'], unique=False)
    op.create_table('seasonal_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_rate_dates'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonal_rates_unit_id'), 'seasonal_rates', ['unit_id'], unique=False)
    op.add_column('units', sa.Column('weekend_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('units', sa.Column('min_stay_nights', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'min_stay_nights')
    op.drop_column('units', 'weekend_price')
    op.drop_index(op.f('ix_seasonal_rates_unit_id'), table_name='seasonal_rates')
    op.drop_table('seasonal_rates')
    op.drop_index(op.f('ix_availability_blocks_unit_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    # ### end Alembic commands ###
