"""phone login: email nullable, phone unique

Revision ID: 8b60cb7ae658
Revises: 29863b201cb1
Create Date: 2026-06-21 21:14:56.511326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b60cb7ae658'
down_revision: Union[str, None] = '29863b201cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosts', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.create_index(op.f('ix_hosts_phone'), 'hosts', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hosts_phone'), table_name='hosts')
    op.alter_column('hosts', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
